### PR TITLE
[#33] fix: PHP 8.1 Deprecation notice: strpos(): Passing null to parameter

### LINKED ISSUE #33: PHP 8.1 Deprecation notice: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
When using this module with PHP 8.1 or more you get the following error:

`Deprecated function: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in Drupal\twig_fractal\NodeVisitors\Attributes->isAttributes() (line 51 of modules/contrib/twig_fractal/src/NodeVisitors/Attributes.php).`

### PR DESCRIPTION
**Pull request by ipwa**
Fixes #33

### CODE REVIEW

File: src/NodeVisitors/Attributes.php [hunk 1]
```diff
@@ -48,8 +48,11 @@ public function doLeaveNode(Node $node, Environment $env): Node {
    * @return \Node|null
    */
   protected function isAttributes($node): ?Node {
-    if ($node->hasAttribute('name') && strpos($node->getAttribute('name'), 'attributes') !== FALSE) {
-      return $node;
+    if ($node->hasAttribute('name')) {
+      $name = (string) $node->getAttribute('name'); // Ensure it's a string
+      if (strpos($name, 'attributes') !== false) {
+        return $node;
+      }
```
Comment (sun) [inline src/NodeVisitors/Attributes.php]:
```suggestion
    if ($node->hasAttribute('name') && strpos((string) $node->getAttribute('name'), 'attributes') !== FALSE) {
      return $node;
```

**Review by sun — CHANGES_REQUESTED** [review]
I assume this is only triggered in development environments where nodes with undefined names can appear.  Nevertheless we can fix it.

Can you shorten the solution as suggested, please?

**Review by sun — APPROVED** [review]
